#!/usr/bin/env sh
echo "🔍 Running lint pre-commit check..."
npm run lint

echo "🔍 Running prettier pre-commit check..."
npm run prettier:check

echo "🔍 Running stylelint pre-commit check..."
npm run stylelint:check
