#!/bin/sh
cd ./next || exit 1

echo ""
echo "🔍 Running lint pre-commit check..."
npm run lint

echo ""
echo "🔍 Running prettier pre-commit check..."
npm run prettier:check

echo ""
echo "🔍 Running stylelint pre-commit check..."
npm run stylelint:check