name: GitHub Actions Tests
run-name: ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
jobs:
  Next-Format-Check:
    name: Next Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./next

      - name: Run ESLint
        run: npm run lint
        working-directory: ./next

      - name: Run Prettier
        run: npm run prettier:check
        working-directory: ./next

      - name: Run Styleint
        run: npm run stylelint:check
        working-directory: ./next